doc fixes: configure says "libusb 0.1.8", usbmodules.8 device path

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5144,8 +5144,8 @@ _ACEOF
   LIBS="-lusb $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: get libusb 1.8 or newer" >&5
-echo "$as_me: error: get libusb 1.8 or newer" >&2;}
+  { { echo "$as_me:$LINENO: error: get libusb 0.1.8 or newer" >&5
+echo "$as_me: error: get libusb 0.1.8 or newer" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
